name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --verbose

  release:
    runs-on: macos-12
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Install x86_64-apple-darwin as release target
        run: rustup target add x86_64-apple-darwin

      - name: Install aarch64-apple-darwin as release target
        run: rustup target add aarch64-apple-darwin

      - name: Build for x86_64-apple-darwin
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build for aarch64-apple-darwin
        run: cargo build --release --target aarch64-apple-darwin

      - uses: actions/upload-artifact@v3
        with:
          name: max-mic-volume-x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release/max-mic-volume

      - uses: actions/upload-artifact@v3
        with:
          name: max-mic-volume-aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/max-mic-volume
